config/routes.rb
Rails.application.routes.draw do
  get 'users/main'
  post 'users/login'
  root 'users#main'
  get 'users/logout'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

end

app/models/user.rb
class User < ApplicationRecord
  validates :uid , uniqueness: true
  def self.authenticate(uid, pass)
    if user = find_by(uid: uid)
      if BCrypt::Password.new(user.pass) == pass
        user
      end
    else
      nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def main
    if session[:login_uid] != nil
      render 'login'
    elsif session[:login_uid] == nil
      render 'main'
    end
  end

  def login
    # p session[:login_uid]

    if User.authenticate(params[:uid], params[:pass])
      session[:login_uid] = params[:uid]
      redirect_to users_main_path
    else
      render 'error'
    end
  end

  def error

  end

  def logout

    session.delete(:login_uid)
    redirect_to users_main_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>L42</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/error.html.erb
<p>エラーです。やり直してください。</p>


<%= link_to "戻る", users_main_path %>

app/views/users/login.html.erb
<h1>ログインしました</h1>
<%=link_to 'ログアウト', users_logout_path %>

app/views/users/main.html.erb
<h1>ログイン画面</h1>
<%= form_tag '/users/login', method: :post do%>
 <%= label_tag :uid, 'ユーザーID' %>
 <%= text_field_tag :uid %>
 <%= label_tag :pass, 'パスワード' %>
 <%= text_field_tag :pass %>

 <%= submit_tag 'ログイン' %>
<%end %>